### ISSUE TITLE
Dark Mode - Canned Reponses List - Change Requests

### ISSUE THREAD

**Issue by darkufo** [avm99963/infinitegforums#12]
Currently in Dark Mode the Canned Responses is very "bright". 

![chrome_vu0ScCKsFT](https://user-images.githubusercontent.com/12990410/92587287-5b0c4f80-f28f-11ea-864d-a9c77dd98fbe.png)

I would like to suggest fading the borders and changing the color the Canned Response title to something like this, which I think makes it a little more readable.

![chrome_RbufEdOX2H](https://user-images.githubusercontent.com/12990410/92587413-8727d080-f28f-11ea-8ada-3812a3b65aa7.png)

**Comment by avm99963** [comment]
With the change I'm going to push in a minute it looks much better than before:

![Screen Shot 2020-11-25 at 19 16 05](https://user-images.githubusercontent.com/682310/100266962-f6d65f00-2f52-11eb-84eb-3dc81d317342.png)

I think in order to get yellowish text it is better to use night mode. However, I think this change already makes that page much less bright.

**Comment by darkufo** [comment]
I agree, looks great. Nice work
